name: neurolabel
channels:
  - conda-forge
dependencies:
  - python 
  - pip
  - numpy
  - pandas
  - pathlib
  - matplotlib
  - scipy
  - functools
  - nilearn
  - nibabel
  - nimare
  - pip:
      - -e ".[dev]"
